/**
 * Phase 2 — recruit funnel + onboarding. All tenant-scoped, so every row carries
 * a `camp_id` (the hard multi-camp invariant).
 *
 *   recruit_application   public application submitted from /c/:slug
 *   camp_invite           tokenized friend-invite link (the secret lives here)
 *   onboarding_task       a checklist item a camp defines for new members
 *   onboarding_completion one row per membership×task once ticked off
 */
import { sql } from "drizzle-orm";
import {
  integer,
  sqliteTable,
  text,
  uniqueIndex,
} from "drizzle-orm/sqlite-core";
import { attendee } from "./attendee";
import { user } from "./auth";
import { camp, membership } from "./camp";
import { prospect } from "./prospect";

const now = sql`(unixepoch() * 1000)`;

export const recruitApplication = sqliteTable("recruit_application", {
  id: text("id").primaryKey(),
  campId: text("camp_id")
    .notNull()
    .references(() => camp.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  email: text("email").notNull(),
  playaName: text("playa_name"),
  // LEGACY (pre question-bank): superseded by seeded application-surfaced
  // camp questions (migration 0052). Kept so old applications still display;
  // no longer written.
  previousCamp: text("previous_camp"),
  previousCampNotes: text("previous_camp_notes"),
  // Application-surfaced questionnaire answers, JSON {questionId: value} —
  // held here because the applicant has no membership yet. Imported into
  // question_answer (and stamped answersImportedAt) once they do.
  answers: text("answers"),
  answersImportedAt: integer("answers_imported_at", { mode: "timestamp_ms" }),
  message: text("message"),
  status: text("status").notNull().default("pending"),
  // Set if the applicant's email matches an existing account.
  userId: text("user_id").references(() => user.id, { onDelete: "set null" }),
  reviewedById: text("reviewed_by_id").references(() => user.id, {
    onDelete: "set null",
  }),
  reviewNotes: text("review_notes"),
  createdAt: integer("created_at", { mode: "timestamp_ms" })
    .notNull()
    .default(now),
  reviewedAt: integer("reviewed_at", { mode: "timestamp_ms" }),
});

// A shareable invite link generated by an existing member. The `token` is the
// secret embedded in the URL (/i/:token); redeeming it joins the camp and
// records who invited whom (the inviter's membership). Public applications
// carry NO token — only these friend-invites do.
export const campInvite = sqliteTable("camp_invite", {
  id: text("id").primaryKey(),
  campId: text("camp_id")
    .notNull()
    .references(() => camp.id, { onDelete: "cascade" }),
  inviterMembershipId: text("inviter_membership_id")
    .notNull()
    .references(() => membership.id, { onDelete: "cascade" }),
  token: text("token").notNull().unique(),
  // The invite's locked type. 'personal' is a one-person door tied to its
  // inviter: maxUses is forced to 1 at creation and the redeemer is recorded
  // as invited by them. 'open' (officer-only) is a camp door: reusable, and
  // joining through it records no personal inviter. The kind never changes
  // after creation.
  kind: text("kind").notNull().default("personal"),
  // Role granted on redemption. Kept to "recruit" for safety: a leaked link
  // must never self-grant elevated access — promote via member management.
  role: text("role").notNull().default("recruit"),
  // Free-text label for who/what the link is for ("For Alex", "2026 art crew
  // channel"). Internal bookkeeping — never shown to the redeemer.
  note: text("note"),
  // Guest promotion (Who's-coming Phase 4): when set, redeeming this invite
  // ADOPTS that guest attendee row — membership_id is set to the new
  // membership, host/name/email cleared — so the guest's RSVP, occupancy,
  // tickets, and passes follow them into the account. If the guest row is
  // deleted first this nulls out and the link redeems as a plain invite.
  promoteAttendeeId: text("promote_attendee_id").references(() => attendee.id, {
    onDelete: "set null",
  }),
  // Prospect promotion (see plans/prospects-crm.md): an invite generated from a
  // prospect's card. Redeeming it stamps that prospect with the new membership
  // and flips it to `joined`, so the officers' conversation history follows the
  // person into the camp instead of being orphaned. Same shape as
  // promoteAttendeeId above; nulls out if the prospect is deleted first, and
  // the link then redeems as a plain invite.
  prospectId: text("prospect_id").references(() => prospect.id, {
    onDelete: "set null",
  }),
  // null = unlimited uses; otherwise redemption stops once useCount hits it.
  maxUses: integer("max_uses"),
  useCount: integer("use_count").notNull().default(0),
  // When the link was most recently redeemed. Kept on the link itself (not
  // derived from redeemer memberships) so the record survives member removal.
  lastUsedAt: integer("last_used_at", { mode: "timestamp_ms" }),
  expiresAt: integer("expires_at", { mode: "timestamp_ms" }),
  revokedAt: integer("revoked_at", { mode: "timestamp_ms" }),
  createdAt: integer("created_at", { mode: "timestamp_ms" })
    .notNull()
    .default(now),
});

export const onboardingTask = sqliteTable("onboarding_task", {
  id: text("id").primaryKey(),
  campId: text("camp_id")
    .notNull()
    .references(() => camp.id, { onDelete: "cascade" }),
  title: text("title").notNull(),
  description: text("description"),
  sortOrder: integer("sort_order").notNull().default(0),
  createdAt: integer("created_at", { mode: "timestamp_ms" })
    .notNull()
    .default(now),
});

export const onboardingCompletion = sqliteTable(
  "onboarding_completion",
  {
    id: text("id").primaryKey(),
    campId: text("camp_id")
      .notNull()
      .references(() => camp.id, { onDelete: "cascade" }),
    membershipId: text("membership_id")
      .notNull()
      .references(() => membership.id, { onDelete: "cascade" }),
    taskId: text("task_id")
      .notNull()
      .references(() => onboardingTask.id, { onDelete: "cascade" }),
    completedAt: integer("completed_at", { mode: "timestamp_ms" })
      .notNull()
      .default(now),
  },
  (t) => [
    uniqueIndex("onboarding_completion_member_task").on(
      t.membershipId,
      t.taskId,
    ),
  ],
);
